### ISSUE TITLE
Create full stack network/system diagrams for miriconf

### ISSUE THREAD

**Issue by g-bolmida** [MiriConf/miriconf-documents#4]
Create network/system diagrams for the connections between services and how the software works using excalidraw or draw.io and push the diagram files and a rendered PDF file for each into https://github.com/MiriConf/miriconf-documents

**Comment by mbayean** [comment]
For this task, I managed to make a network diagram that shows the communication between the frontend and the backend by specifically showing how the user's request is being executed across the whole network from the UI passing through the backend to the database
